AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: JSON string
Parameters:
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - qa
      - staging
      - prod
  AppName:
    Type: String
  VpcCidr:
    Type: String
    Description: Network subnet for routing
    Default: '10.61.0.0/16'
  VpcNamesForPrivate:
    Type: CommaDelimitedList
    Description: List for names of private subnets
    Default: 'A,B,C'
  VpcNamesForPublic:
    Type: CommaDelimitedList
    Description: List for names of public subnets
    Default: 'A'
  VpcMaskForPrivate:
    Type: String
    Description: Mask to apply to private subnets
    Default: '/24'
  VpcMaskForPublic:
    Type: String
    Description: Mask to apply to public subnets
    Default: '/24'
  UpdateSubnetCidr:
    Type: String
    AllowedValues:
         - 'true'
         - 'false'
    Default: 'false'
Mappings:
  PrivateSubnetMap:
    A:
      CidrIp:
        Fn::Transform:
          Name: 'subnet-generator'
          Parameters:
            VpcCidr: !Ref VpcCidr
            SubnetMask: !Ref VpcMaskForPrivate
            CacheBreaker: 'A'
    B:
      CidrIp:
        Fn::Transform:
          Name: 'subnet-generator'
          Parameters:
            VpcCidr: !Ref VpcCidr
            SubnetMask: !Ref VpcMaskForPrivate
            CacheBreaker: 'B'
    C:
      CidrIp:
        Fn::Transform:
          Name: 'subnet-generator'
          Parameters:
            VpcCidr: !Ref VpcCidr
            SubnetMask: !Ref VpcMaskForPrivate
            CacheBreaker: 'C'
  PublicSubnetMap:
    A:
      CidrIp:
        Fn::Transform:
          Name: 'subnet-generator'
          Parameters:
            VpcCidr: !Ref VpcCidr
            SubnetMask: !Ref VpcMaskForPublic
    B:
      CidrIp:
        Fn::Transform:
          Name: 'subnet-generator'
          Parameters:
            VpcCidr: !Ref VpcCidr
            SubnetMask: !Ref VpcMaskForPublic
    C:
      CidrIp:
        Fn::Transform:
          Name: 'subnet-generator'
          Parameters:
            VpcCidr: !Ref VpcCidr
            SubnetMask: !Ref VpcMaskForPublic

Conditions:
  UpdateSubnets: !Equals [!Ref UpdateSubnetCidr, 'true']

Resources:
  SSMVpcNetworkCidr:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${AppName}/vpc-networking/cidr'
      Tier: Standard
      Type: String
      Value: !Ref VpcCidr
  'Fn::ForEach::PrivateSubnets':
    - SubnetName
    - !Ref VpcNamesForPrivate
    - 'SSMCidrNetworkPrivateSubnet${SubnetName}':
        Type: 'AWS::SSM::Parameter'
        Condition: UpdateSubnets
        Properties:
          Name: !Sub '/config/infra/${AppName}/vpc-networking/cidr-private-subnet/${SubnetName}'
          Tier: Standard
          Type: String
          Value: !FindInMap 
            - PrivateSubnetMap
            - !Ref SubnetName
            - CidrIp
  'Fn::ForEach::PublicSubnets':
    - SubnetName
    - !Ref VpcNamesForPublic
    - 'SSMCidrNetworkPublicSubnet${SubnetName}':
        Type: 'AWS::SSM::Parameter'
        Condition: UpdateSubnets
        Properties:
          Name: !Sub '/config/infra/${AppName}/vpc-networking/cidr-public-subnet/${SubnetName}'
          Tier: Standard
          Type: String
          Value: !FindInMap 
            - PublicSubnetMap
            - !Ref SubnetName
            - CidrIp
  