AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: JSON string
Parameters:
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - qa
      - staging
      - prod
  AppName:
    Type: String
  VpcCidr:
    Type: String
    Description: Network subnet for routing
    Default: '10.61.0.0/16'
  VpcNamesForPrivate:
    Type: CommaDelimitedList
    Description: List for names of private subnets
    Default: 'A, B, C'
  VpcNamesForPublic:
    Type: CommaDelimitedList
    Description: List for names of public subnets
    Default: 'A, '
  
Resources:
  SSMVpcBusinessCidr:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${AppName}/vpc-business/cidr'
      Tier: Standard
      Type: String
      Value: !Ref VpcCidr
  'Fn::ForEach::Topics':
    - SubnetName
    - !Ref VpcNamesForPrivate
    - 'SSMCidrBusinessPrivateSubnet${SubnetName}':
        Type: 'AWS::SSM::Parameter'
        Properties:
          Name: !Sub '/config/infra/${AppName}/vpc-business/cidr-private-subnet/${SubnetName}'
          Tier: Standard
          Type: String
          Value: !Ref SubnetName
    
    - SubnetName
    - !Ref VpcNamesForPublic
    - 'SSMCidrBusinessPublicSubnet${SubnetName}':
        Type: 'AWS::SSM::Parameter'
        Properties:
          Name: !Sub '/config/infra/${AppName}/vpc-business/cidr-public-subnet/${SubnetName}'
          Tier: Standard
          Type: String
          Value: !Ref SubnetName
  