AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: JSON string
Parameters:
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - qa
      - staging
      - prod
  AppName:
    Type: String
  VpcCidr:
    Type: String
    Description: Network subnet for routing
    Default: '10.61.0.0/16'
  VpcNamesForPrivate:
    Type: CommaDelimitedList
    Description: List for names of private subnets
    Default: 'A,B,C'
  VpcNamesForPublic:
    Type: CommaDelimitedList
    Description: List for names of public subnets
    Default: 'A'

Mappings:
  PrivateSubnetMap:
    A:
      CidrIp: '10.11.12.0'
    B:
      CidrIp: '10.11.22.0'
    C:
      CidrIp: '10.11.32.0'
  PublicSubnetMap:
    A:
      CidrIp: '10.11.42.0'
    B:
      CidrIp: '10.11.52.0'
    C:
      CidrIp: '10.11.62.0'
  
Resources:
  SSMVpcBusinessCidr:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${AppName}/vpc-business/cidr'
      Tier: Standard
      Type: String
      Value: !Ref VpcCidr
  'Fn::ForEach::PrivateSubnets':
    - SubnetName
    - !Ref VpcNamesForPrivate
    - 'SSMCidrBusinessPrivateSubnet${SubnetName}':
        Type: 'AWS::SSM::Parameter'
        Properties:
          Name: !Sub '/config/infra/${AppName}/vpc-business/cidr-private-subnet/${SubnetName}'
          Tier: Standard
          Type: String
          Value: !FindInMap 
            - PrivateSubnetMap
            - !Ref SubnetName
            - CidrIp
  'Fn::ForEach::PublicSubnets':
    - SubnetName
    - !Ref VpcNamesForPublic
    - 'SSMCidrBusinessPublicSubnet${SubnetName}':
        Type: 'AWS::SSM::Parameter'
        Properties:
          Name: !Sub '/config/infra/${AppName}/vpc-business/cidr-public-subnet/${SubnetName}'
          Tier: Standard
          Type: String
          Value: !FindInMap 
            - PublicSubnetMap
            - !Ref SubnetName
            - CidrIp
  