AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack for macros
Parameters:
  EnvironmentName:
    Type: String
  AppName:
    Type: String
  BucketName:
    Type: String

Resources:
  StackReadSSMFromPath:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.${AWS::URLSuffix}/${AppName}/deploys/networking-db/cfn_macros/ssm-params/from_path/register_macro.yaml'
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
      TimeoutInMinutes: 60

  StackMapArrayString:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.${AWS::URLSuffix}/${AppName}/deploys/networking-db/cfn_macros/operation_array/map/register_macro.yaml'
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
      TimeoutInMinutes: 60
  
  StackSubnetGenerator:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.${AWS::URLSuffix}/${AppName}/deploys/networking-db/cfn_macros/subnet_gen/register_macro.yaml'
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
      TimeoutInMinutes: 60
  
  StackValidateSubnetGenerator:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.${AWS::URLSuffix}/${AppName}/deploys/networking-db/cfn_macros/ssm-params/validate_exists_subnet/register_macro.yaml'
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
      TimeoutInMinutes: 60
