AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: Internet Gateway configuration infra
Parameters:

  Name:
    Type: String
    Description: An environment name that will be prefixed to resource names

  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the security groups should be deployed to

  PublicSubnets:
    Type: CommaDelimitedList
    Description: List of names of network subnets

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Name}-ig

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCID

  #This One
  'Fn::ForEach::ElasticIPs':
    - SubnetName
    - !Ref PublicSubnets
    - 'ElasticIP${SubnetName}':
        Type: AWS::EC2::EIP
        DependsOn: InternetGatewayAttachment
        Properties:
          Domain: vpc
          Tags:
            - Key: Name
              Value: !Sub ${Name}-eip-${SubnetName}

  'Fn::ForEach::NatGateways':
    - SubnetName
    - !Ref PublicSubnets
    - 'NatGateway${SubnetName}':
        Type: AWS::EC2::NatGateway
        Properties:
          AllocationId: !GetAtt 
            - !Sub 'ElasticIP${SubnetName}'
            - AllocationId
          SubnetId: !Sub '{{resolve:ssm:/config/infra/${Name}/public_subnet/${SubnetName}}}'
          Tags:
            - Key: Name
              Value: !Sub ${Name}-nat-${SubnetName}
  
  'Fn::ForEach::NatGatewaysSSM':
    - SubnetName
    - !Ref PublicSubnets
    - 'NatGateway${SubnetName}-SSM':
        Type: AWS::SSM::Parameter
        Properties:
          Name: !Sub "/config/infra/${Name}/ng/${SubnetName}"
          Type: String
          Value: !GetAtt 
            - !Sub 'NatGateway${SubnetName}'
            - NatGatewayId


Outputs:
  StackName:
    Value: !Sub '${AWS::StackName}'

  InternetGateway:
    Value: !Ref InternetGateway

  'Fn::ForEach::NatGatewayOutputs':
    - SubnetName
    - !Ref PublicSubnets
    - 'NatGateway${SubnetName}':
        Value: !GetAtt 
          - !Sub 'NatGateway${SubnetName}'
          - NatGatewayId
        Export:
          Name: !Sub '${AWS::StackName}-NatGateway${SubnetName}'